name: ternary_plot
description: 'A Flutter package to create ternary/triangle plot.'
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.0-0
  flutter: '>=1.17.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
